name: Test Form (do not use)
description: Create a bug
title: "[Tool name: bug behavior...]"
labels: ["A-bug", "B-moderate", "C-dev", "C-test"]
assignees:
  - scot7557
body:
  - type: textarea
    id: what-happened
    attributes:
      label: "Bug Description:"
      description: Tell us which tool or feature has the bug and include a short and specific summary of issue.
      placeholder: 
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce:"
      description: Tell us the exact steps to reproduce the bug and location of the data, if required.
      value: |
        data path: \\archive\crdata\ArcGISPro\editing\
        
        1.
        
  - type: textarea
    id: what-should-happen
    attributes:
      label: "Expected behavior:"
      description: Tell us what should happen, or how the tool/feature used to work before a regression started.
      placeholder: 
  - type: input
    id: version
    attributes:
      label: "Build first reproduced:"
      description: What version and build of Pro did you first reproduce?
  - type: dropdown
    id: build-q
    attributes:
      label: "Is this a regression?"
      description: If so, be sure to add "T-z Regression" label and include the build it started in the "More build details" section below.
      options:
        - "Not sure"
        - "Yes"
        - "No"
      default: 0
  - type: textarea
    id: build-details
    attributes:
      label: "More build details:"
      description: What build did a regression start? What builds did you test and reproduce or not?
      placeholder: |
        Build a regression started
        Info about builds that you tested and reproduced or not
  - type: dropdown
    id: failing-test-q
    attributes:
      label: "Are there any failing automated tests?"
      description: If so, please add failing test info in the "Additional information" section below and add the "T-Automated Testing 35" label.
      options:
        - "Not sure"
        - "Yes"
        - "No"
      default: 0
  - type: textarea
    id: additional-info
    attributes:
      label: "Additional information:"
      description: Provide additional info here
      value: |
        Failing test info:
        
        Additional Test Cases:
        
        Related issues:
        
        Break out issues:
        
        Patch Target Releases:
        
        Patch in Releases:

        WRR checklist:
        - [ ] wrr draft
        - [ ] justification / impact
        - [ ] tech details
        - [ ] test plan

  
