name: Test Form (do not use)
description: Create a bug
title: "[Tool name: bug behavior...]"
labels: ["A-bug", "B-moderate", "C-dev", "C-test"]
assignees:
  - scot7557
body:
  - type: textarea
    id: what-happened
    attributes:
      label: "Bug Description:"
      description: Tell us which tool or feature has the bug and include a short and specific summary of issue.
      placeholder: 
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Tell the exact steps to reproduce the bug and location of the data, if required.
      value: |
        data path: \\archive\crdata\ArcGISPro\editing\
        
        1.
        
  - type: textarea
    id: what-should-happen
    attributes:
      label: Expected behavior
      description: Tell us what should happen, or how the tool/feature used to work before a regression started.
      placeholder: 
  - type: input
    id: version
    attributes:
      label: Version and build
      description: What version of Pro did you first reproduce?
  - type: dropdown
    id: build-q
    attributes:
      label: Regression?
      options:
        - "Not sure"
        - "Yes"
        - "No"
      default: 0
  - type: textarea
    id: build-details
    attributes:
      label: More build details
      description: Provide more build details here
      placeholder: |
        What build did a regression start?
        If you don't know, please find out and add this info later.
  - type: dropdown
    id: failing-test-q
    attributes:
      label: Is there a failing test?
      description: If so, please add the "T-Automated Testing 35" label.
      options:
        - "Not sure"
        - "Yes"
        - "No"
      default: 0
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Provide additional info here
      value: |
        Additional Test Cases:
        
        Related issues:
        
        Break out issues:
        
        Patch Target Releases:
        
        Patch in Releases:

        WRR checklist:
        - [ ] wrr draft
        - [ ] justification / impact
        - [ ] tech details
        - [ ] test plan

  
